### PR TITLE
Update to Ace 1.2.3 and Using Ace Sessions

### PR DESCRIPTION
**Pull request by STRd6**
Update to be compatible with Ace 1.2+ and to use Ace sessions to better enable multi-document editing in the future.

This is still a bit of a work in progress, but I thought I'd open it early for feedback and to gauge interest.

Goals:
- [x] Update to be compatible with latest Ace
- [x] Use ace edit sessions rather than binding one document to the whole editor (this will make switching documents while maintaining sessions easier)
- [ ] Update the bundled Ace library
- [ ] Currently disabled "readOnly" mode because it's not per session but there should be a way to get it back if we need to

Bonus Goals:
- Use a single websocket rather than destroying and recreating the websocket every document change
- Communicate only over the websocket rather than out of band http requests
- Preload documents and track OT for all documents so clients can experience instantaneous document switching
- Improve user document and cursor tracking so that it is lower latency but also less chatty when the cursor hasn't changed

The bonus goals are ultimately the direction I'd like to go, but I understand that there are trade-offs involved and won't be offended if there is no interest. I figured I'd ask early! At least the Ace updates and switiching to using Ace sessions should provide some more flexibility.

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @STRd6, looks great! The session API seems cleaner so I'd like to add this in. Those bonus goals seem sensible, I'd also be in favor of shaking up the API to be more efficient.

**Comment by STRd6** [comment]
Cool, glad to hear the positive support. I'll be poking away at this over the next couple of weeks and try to keep the PR up to date.

**Comment by Jeffail** [comment]
Hey @STRd6, I've made a few major changes since this pull request was opened. I've temporarily switched to CodeMirror as the editor of choice since I cannot currently get surrogate pair characters to work correctly with ACE. I've also done a major rework of the websockets API so that client to client coms can be simplified, including lazy reporting of cursor positions (only when it changes or new clients connect).

I've implemented the API such that we could have multiple subscriptions on the same websocket in the future without breaking anything. It would still require some minor client and server updates but the coms between them should stay mostly the same.

I'm leaving it as is for now, but my intention would be to revisit ACE if the UTF-16 limitations can be fixed, then have another pass at this. I'll close this pull request for now but just wanted to say thank you very much as I did use this branch for testing the newer ACE version.

**Comment by STRd6** [comment]
Cool, thanks for looping back around, I've run out of time to continue on this, but I'm glad it was of some use :)

**Pull request closed without merging**
